name: PR Validation

on:
  pull_request:
    branches: [main, master]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Audit Dependencies
        run: pnpm audit --audit-level=moderate
        continue-on-error: true

      - name: Lint
        run: pnpm run lint

      - name: Compile
        run: pnpm run compile

      - name: Compile Tests
        run: pnpm run test-compile

      - name: Copy Test Runner
        run: |
          mkdir -p out/test
          cp src/test/runTest.js out/test/

      - name: Run Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pnpm run test
          working-directory: ${{ github.workspace }}

      - name: Build Extension
        run: pnpm run package

      - name: Check Bundle Size
        run: |
          BUNDLE_SIZE=$(stat -c%s dist/extension.js)
          echo "Bundle size: $BUNDLE_SIZE bytes"
          echo "BUNDLE_SIZE=$BUNDLE_SIZE" >> $GITHUB_ENV

      - name: Package VSIX
        run: pnpm dlx vsce package --no-dependencies

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-package-json-manager-vsix
          path: "*.vsix"
          retention-days: 7
