name: PR Validation

on:
  pull_request:
    branches: [main, master]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
        
      - name: Compile
        run: npm run compile

      - name: Run Tests
        run: npm run test
        
      - name: Build Extension
        run: npm run package
        
      - name: Package VSIX
        run: npx vsce package --no-dependencies
        
      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-package-json-manager-vsix
          path: "*.vsix"